### PR TITLE
PCB1_A64_MAIN_REV_C: Translated in English

### PR DESCRIPTION
**Pull request by Kreyren**
The manufacturer that I sent this to was confused by the bulgarian so I translated this in english.

### CODE REVIEW

**Comment by Kreyren** [comment]
CC @TsvetanUsunov @jcstaudt @hehopmajieh @trygvis Assumed maintainers of the repository

Note: Was told in #olimex on irc that mentioning people might be understood as rude which is not my intention, the motivation for mentioning are mitigation for GH not sending notifications which is my personal experience + practice with working on non-GH platforms

**Comment by TsvetanUsunov** [comment]
looks good

**Comment by DanKoloff** [comment]
There is still Bulgarian left over, see positions #78 and #82 and #84. Also - not everyone has OpenOffice or LibreOffice, hence why we used to publish these as PDF.

**Comment by Kreyren** [comment]
> There is still Bulgarian left over, see positions #78 and #82 and #84. -- @DanKoloff (https://github.com/OLIMEX/DIY-LAPTOP/pull/46#issuecomment-1247692560)

I don't know how to translate those to english.

> Also - not everyone has OpenOffice or LibreOffice, hence why we used to publish these as PDF. -- @DanKoloff (https://github.com/OLIMEX/DIY-LAPTOP/pull/46#issuecomment-1247692560)

I was told that proprietary alternatives are able to open libre formats, but i don't have the software to confirm that.

**Comment by DanKoloff** [comment]
Browsers can open PDF... also PDF is directly visualized in GitHub... and this is not the case with ODG... and while PDF used to be propriety, this is no longer the case. So there is not much going on for ODG over PDF. Anyway, good catch on the Bulgarian, we shouldn't have Bulgarian in our documents, but sometimes the developers and myself don't check thoroughly. Still it is a good sign that we publish the same documents that we use in our work and manufacturing and we don't alter our open source design before publishing online.

**Comment by xloem** [comment]
82 SMD TVS DIODE SMBJ6.0A

**Pull request merged**
